include: package:flutter_lints/flutter.yaml

linter:
  rules:
    ## DART RULES ##
    prefer_relative_imports: true
    avoid_print: true
    prefer_single_quotes: true
    curly_braces_in_flow_control_structures: true
    always_declare_return_types: true
    prefer_final_fields: true
    prefer_const_constructors: true
    prefer_final_locals: true
    unnecessary_async: true
    unnecessary_new: true
    unnecessary_await_in_return: true
    unnecessary_breaks: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    sort_pub_dependencies: true
    directives_ordering: true
    unnecessary_null_checks: true
    prefer_collection_literals: true
    avoid_unused_constructor_parameters: true
    prefer_function_declarations_over_variables: true
    require_trailing_commas: true
    camel_case_types: true
    constant_identifier_names: true
    file_names: true
    library_names: true
    non_constant_identifier_names: true
    prefer_interpolation_to_compose_strings: true
    prefer_typing_uninitialized_variables: true
    use_rethrow_when_possible: true
    avoid_renaming_method_parameters: true
    avoid_returning_null_for_void: true
    avoid_types_as_parameter_names: true

    ## Flutter Rules ##
    avoid_unnecessary_containers: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
    sized_box_for_whitespace: true
    use_build_context_synchronously: true
    use_key_in_widget_constructors: true
    avoid_redundant_argument_values: true
    prefer_if_null_operators: true
    prefer_null_aware_operators: true
    prefer_final_in_for_each: true
    sort_child_properties_last: true
    use_decorated_box: true
    use_late_for_private_fields_and_variables: true
    use_full_hex_values_for_flutter_colors: true
    prefer_const_declarations: true
    flutter_style_todos: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
