name: flutter_clean_architecture
description: "Flutter Clean Architecture Boilerplate"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  hive_ce: ^2.11.4
  hive_ce_flutter: ^2.3.2
  logger: ^2.6.1
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.7.1
  flutter_flavorizr: ^2.4.1
  flutter_gen: ^5.11.0
  flutter_gen_runner: ^5.11.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.9.3
  mocktail: ^1.0.4
  
flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:
      bundleId: "com.example.flutterCleanArchitecture"

  flavors:
    dev:
      app:
        name: "Flutter Clean Architecture Dev"
      android:
        applicationId: "com.example.flutter_clean_architecture.dev"
      ios:
        bundleId: "com.example.flutterCleanArchitecture.dev"
      main: "main_dev.dart"
    staging:
      app:
        name: "Flutter Clean Architecture Staging"
      android:
        applicationId: "com.example.flutter_clean_architecture.staging"
      ios:
        bundleId: "com.example.flutterCleanArchitecture.staging"
      main: "main_staging.dart"
    prod:
      app:
        name: "Flutter Clean Architecture Prod"
      android:
        applicationId: "com.example.flutter_clean_architecture"
      ios:
        bundleId: "com.example.flutterCleanArchitecture"
      main: "main_prod.dart"

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/gen/
  line_length: 80

