name: gen_module_hooks
description: Hooks for gen_module brick.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  mason: ^0.1.1

dev_dependencies:
  lints: ^4.0.0
